[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
build_flags = 
    -D MQTT_MAX_PACKET_SIZE=512
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8